# Generated by Django 3.0.5 on 2020-04-25 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_published',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='img',
            field=models.ImageField(default='img/chatbot.png', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='quote',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
