# Generated by Django 3.0.5 on 2020-04-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200426_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='allow_comments',
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
